from .telegram_user import TelegramUser
from .user import User
from .admin import Admin
from .bot import Bot
from .admin_tariff import AdminTariff
from .user_tariff import UserTariff
from .payment_admin import PaymentAdmin
from .payment_user import PaymentUser
from .promo import Promo